name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Project Files
        run: |
          unzip -o SCEditorAndroid.zip -d .
          # Se o zip criou uma pasta extra, movemos os arquivos para a raiz
          if [ -d "SCEditorAndroid" ]; then
            mv SCEditorAndroid/* .
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sc-editor-apk
          path: app/build/outputs/apk/debug/*.apk
